// <auto-generated />
using System;
using LibraryApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryApi.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260324095705_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Emprunt", b =>
                {
                    b.Property<int>("Id_Emprunt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Emprunt"));

                    b.Property<DateTime>("DateRetourPrevue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRetourReelle")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_Emprunt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EtudiantId_etudiant")
                        .HasColumnType("int");

                    b.Property<int>("Id_Livre")
                        .HasColumnType("int");

                    b.Property<int>("Id_etudiant")
                        .HasColumnType("int");

                    b.Property<int?>("LivreId_Livre")
                        .HasColumnType("int");

                    b.HasKey("Id_Emprunt");

                    b.HasIndex("EtudiantId_etudiant");

                    b.HasIndex("LivreId_Livre");

                    b.ToTable("Emprunts");
                });

            modelBuilder.Entity("Etudiant", b =>
                {
                    b.Property<int>("Id_etudiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_etudiant"));

                    b.Property<int>("CEF")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FillierId_Fillier")
                        .HasColumnType("int");

                    b.Property<int>("Id_Fillier")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_etudiant");

                    b.HasIndex("FillierId_Fillier");

                    b.ToTable("Etudiants");
                });

            modelBuilder.Entity("Fillier", b =>
                {
                    b.Property<int>("Id_Fillier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Fillier"));

                    b.Property<string>("NomFillier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Fillier");

                    b.ToTable("Filliers");
                });

            modelBuilder.Entity("LibraryApi.Models.Categorie", b =>
                {
                    b.Property<int>("Id_Categorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Categorie"));

                    b.Property<string>("NomCategorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Categorie");

                    b.ToTable("Categorie", (string)null);
                });

            modelBuilder.Entity("LibraryApi.Models.Livre", b =>
                {
                    b.Property<int>("Id_Livre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Livre"));

                    b.Property<int>("Annee")
                        .HasColumnType("int");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Categorie")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Livre");

                    b.HasIndex("Id_Categorie");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibraryApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Emprunt", b =>
                {
                    b.HasOne("Etudiant", "Etudiant")
                        .WithMany("Emprunts")
                        .HasForeignKey("EtudiantId_etudiant");

                    b.HasOne("LibraryApi.Models.Livre", "Livre")
                        .WithMany()
                        .HasForeignKey("LivreId_Livre");

                    b.Navigation("Etudiant");

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("Etudiant", b =>
                {
                    b.HasOne("Fillier", "Fillier")
                        .WithMany("Etudiants")
                        .HasForeignKey("FillierId_Fillier");

                    b.Navigation("Fillier");
                });

            modelBuilder.Entity("LibraryApi.Models.Livre", b =>
                {
                    b.HasOne("LibraryApi.Models.Categorie", "Categorie")
                        .WithMany("Livres")
                        .HasForeignKey("Id_Categorie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Etudiant", b =>
                {
                    b.Navigation("Emprunts");
                });

            modelBuilder.Entity("Fillier", b =>
                {
                    b.Navigation("Etudiants");
                });

            modelBuilder.Entity("LibraryApi.Models.Categorie", b =>
                {
                    b.Navigation("Livres");
                });
#pragma warning restore 612, 618
        }
    }
}
