// <auto-generated />
using System;
using LibraryApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryApi.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryApi.Models.Categorie", b =>
                {
                    b.Property<int>("Id_Categorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Categorie"));

                    b.Property<string>("NomCategorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Categorie");

                    b.ToTable("Categorie", (string)null);
                });

            modelBuilder.Entity("LibraryApi.Models.Emprunt", b =>
                {
                    b.Property<int>("Id_Emprunt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Emprunt"));

                    b.Property<DateTime>("DateRetourPrevue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRetourReelle")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date_Emprunt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Livre")
                        .HasColumnType("int");

                    b.Property<int>("Id_etudiant")
                        .HasColumnType("int");

                    b.HasKey("Id_Emprunt");

                    b.HasIndex("Id_Livre");

                    b.HasIndex("Id_etudiant");

                    b.ToTable("Emprunt", (string)null);
                });

            modelBuilder.Entity("LibraryApi.Models.Etudiant", b =>
                {
                    b.Property<int>("Id_etudiant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_etudiant"));

                    b.Property<int>("Cef")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FillierId_Fillier")
                        .HasColumnType("int");

                    b.Property<int>("Id_Fillier")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_etudiant");

                    b.HasIndex("FillierId_Fillier");

                    b.HasIndex("Id_Fillier");

                    b.ToTable("Etudiant", (string)null);
                });

            modelBuilder.Entity("LibraryApi.Models.Fillier", b =>
                {
                    b.Property<int>("Id_Fillier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Fillier"));

                    b.Property<string>("NomFillier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Fillier");

                    b.ToTable("Fillier", (string)null);
                });

            modelBuilder.Entity("LibraryApi.Models.Livre", b =>
                {
                    b.Property<int>("Id_Livre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Livre"));

                    b.Property<int>("Annee")
                        .HasColumnType("int");

                    b.Property<string>("Auteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Categorie")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Livre");

                    b.HasIndex("Id_Categorie");

                    b.ToTable("Livre", (string)null);
                });

            modelBuilder.Entity("LibraryApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("LibraryApi.Models.Emprunt", b =>
                {
                    b.HasOne("LibraryApi.Models.Livre", "Livre")
                        .WithMany()
                        .HasForeignKey("Id_Livre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryApi.Models.Etudiant", "Etudiant")
                        .WithMany("Emprunts")
                        .HasForeignKey("Id_etudiant")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etudiant");

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("LibraryApi.Models.Etudiant", b =>
                {
                    b.HasOne("LibraryApi.Models.Fillier", "Fillier")
                        .WithMany()
                        .HasForeignKey("FillierId_Fillier");

                    b.HasOne("LibraryApi.Models.Fillier", null)
                        .WithMany("Etudiants")
                        .HasForeignKey("Id_Fillier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fillier");
                });

            modelBuilder.Entity("LibraryApi.Models.Livre", b =>
                {
                    b.HasOne("LibraryApi.Models.Categorie", "Categorie")
                        .WithMany("Livres")
                        .HasForeignKey("Id_Categorie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("LibraryApi.Models.Categorie", b =>
                {
                    b.Navigation("Livres");
                });

            modelBuilder.Entity("LibraryApi.Models.Etudiant", b =>
                {
                    b.Navigation("Emprunts");
                });

            modelBuilder.Entity("LibraryApi.Models.Fillier", b =>
                {
                    b.Navigation("Etudiants");
                });
#pragma warning restore 612, 618
        }
    }
}
